export const ADD_TO_WATCHLIST = "ADD_TO_WATCHLIST";
export const REMOVE_TO_WATCHLIST = "REMOVE_TO_WATCHLIST";
export const ADD_TO_WATCHEDLIST = "ADD_TO_WATCHEDLIST";
export const REMOVE_TO_WATCHEDLIST = "REMOVE_TO_WATCHEDLIST";
export const MOVE_TO_WATCHEDLIST = "MOVE_TO_WATCHEDLIST"